# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-08 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20160606_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='features',
            field=models.ManyToManyField(to='catalog.FeatureKey', verbose_name='Feature Key'),
        ),
    ]
