# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-08 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_category_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurekey',
            name='kind',
            field=models.CharField(choices=[(b'choice', 'Choice'), (b'range', 'Range'), (b'bool', 'Bool')], max_length=10, verbose_name='Kind'),
        ),
    ]
