# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 06:20
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20160608_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retail_price', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=16, verbose_name='Retail price')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.0000'), max_digits=16, null=True, verbose_name='Discount price')),
                ('rent_from', models.DateTimeField(verbose_name='Rent from')),
                ('rent_to', models.DateTimeField(verbose_name='Rent to')),
                ('rent_count', models.IntegerField(verbose_name='Rent count')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='price_for',
            field=models.CharField(choices=[(b'one', 'For one'), (b'kg', 'Kilogram'), (b'day', 'Day')], default=b'one', max_length=50, verbose_name='Price for'),
        ),
        migrations.AddField(
            model_name='rent',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Product', verbose_name='Product'),
        ),
    ]
