# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20170317_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='discount_price',
            new_name='retail_price_with_discount',
        ),
        migrations.AlterField(
            model_name='category',
            name='features',
            field=models.ManyToManyField(blank=True, to='catalog.FeatureKey', verbose_name='Feature Key'),
        ),
    ]
